name: "Deploy Task Script (composite)"
description: "Deploys the task script to the correct environment"
inputs:
  aws_access_key:
    description: "AWS Access Key required for publishing task scripts"
    required: true
  aws_access_key_secret:
    description: "AWS secret for the provided access key"
    required: true
  ssh_key:
    description: "SSH Key for pulling images into the task-script image being published"
    required: true
  # FIXME: what is the best strategy for these?  Force users to specify or rely on them being in the env?
  # FIXME: I would prefer if they could be built into the action repo
runs:
  using: "composite"
  steps:
    - name: Validate input
      shell: bash
      run: |
        echo "--- NOTHING ---"
        echo "" | sha256sum
        echo "--- SSH ---"
        echo "${{ inputs.ssh_key }}" | sha256sum
        echo "${{ inputs.ssh_key }}" | wc
        echo "--- AWS KEY ---"
        echo "${{ inputs.aws_access_key }}" | sha256sum
        echo "$AWS_ACCESS_KEY_ID" | sha256sum"
        echo "${{ inputs.aws_access_key }}" | wc -c

        echo "--- AWS 2 ---"
        echo "${{ inputs.aws_access_key_secret }}" | sha256sum
        echo "$AWS_SECRET_ACCESS_KEY" | sha256sum
        echo "${{ inputs.aws_access_key_secret }}" | wc -c

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ inputs.ssh_key }}
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: composite
        repository: tetrascience/ts-data-insights-ci-cd-common
        ref: DE-3314-github-action
    - name: Setup Node
      uses: actions/setup-node@v2
    - name: Test installs
      shell: bash
      run: |
        aws --version
        docker --version
    - name: Do stuff
      shell: bash
      run: |
        pwd
        ls -altr
        echo "COMPOSITE"
        ls -altr composite
        echo "moving to deploy script location"
        cd composite/actions/deploy-task-script
        pwd
        ls -altr
        yarn install --prod --frozen-lockfile
        yarn global add $PWD
        cd $GITHUB_WORKSPACE
        pwd
        echo "BACK AT $GITHUB_WORKSPACE, about to deploy"
        deploy-task-script

# -      - run: git config --global url."https://${{ secrets.ALEX_PERSONAL_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
# -      - name: Install stuff
# -        env:
# -          SSH_SECRET: ${{ secrets.ALEX_PERSONAL_KEY }}
# -          # Needs to be in a directory that is not the main code directory
# -          SSH_SECRET_DIR: "/home/runner/.ssh_secret"
# -          SSH_SECRET_FILE: "secret_ssh_key"
# -          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
# -          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
# -        run: |
# -          echo "Onwards!"
# -          echo "::group::Setup"
# -          export SSH_KEY_PATH="${SSH_SECRET_DIR}/${SSH_SECRET_FILE}"
# -          mkdir -p $SSH_SECRET_DIR
# -          echo "$SSH_SECRET" > $SSH_KEY_PATH
# -          cat $SSH_KEY_PATH | sha256sum
# -          echo "::endgroup::"
# -          echo "::group::Yarn install"
# -          npm install -g yarn
# -          yarn install --frozen-lockfile --prod
# -          echo "::endgroup::"
# -          echo "::group::ABC Test"
# -          yarn run abctest
# -          echo "::endgroup::"
# -          echo "::group::Deploy"
# -          yarn run deploy:ci
# -          echo "::endgroup::"
