name: "Deploy Task Script"
description: "Deploys the task script to the correct environment"
inputs:
  aws_access_key:
    description: "AWS Access Key required for publishing task scripts"
    required: true
  aws_access_key_secret:
    description: "AWS secret for the provided access key"
    required: true
  ssh_key:
    description: "SSH Key for pulling images into the task-script image being published"
  # FIXME: what is the best strategy for these?  Force users to specify or rely on them being in the env?
  # FIXME: I would prefer if they could be built into the action repo
runs:
  using: "docker"
  image: "Dockerfile"
