name: "Deploy Task Script"
description: "Deploys the task script to the correct environment"
inputs:
  aws_access_key:
    description: "AWS Access Key required for publishing task scripts"
    required: true
  aws_access_key_secret:
    description: "AWS secret for the provided access key"
    required: true
  ssh_key:
    description: "SSH Key for pulling images into the task-script image being published"
runs:
  using: "docker"
  image: "Dockerfile"
